@startuml
!define table(x) class x << (T,#FFAAAA) >>
!define primary_key(x) <color:red>◆</color> x
!define foreign_key(x) <color:blue>◇</color> x

hide methods
hide stereotypes
skinparam classFontColor red
skinparam classAttributeIconSize 0
skinparam defaultFontName Courier

table(Session) {
    primary_key(session_id):  INTEGER
    foreign_key(location_id): INTEGER
    session_date:  DATE
    start_time:    TIMESTAMP
    end_time:      TIMESTAMP
    description:   TEXT
}

table(SetToSession) {
    foreign_key(session_id): INTEGER
    foreign_key(set_id):     INTEGER
    set_index:    INTEGER
}

table(Location) {
    primary_key(location_id): INTEGER
    description:   TEXT
    address:       VARCHAR_255
    url:           VARCHAR_255
}

table(SetTable) {
    primary_key(set_id):    INTEGER
    description: TEXT
}

table(TuneToSet) {
    foreign_key(tune_id): INTEGER
    foreign_key(set_id):  INTEGER
    tune_index:INTEGER
}

table(Tune) {
    primary_key(tune_id): INTEGER
    name:      VARCHAR_255
    abc_path:  VARCHAR_255
    key:       VARCHAR_255
}

Session::location_id --o Location::location_id
Session::session_id o- SetToSession::session_id
SetToSession::set_id -o SetTable::set_id
SetTable::set_id o- TuneToSet::set_id
TuneToSet::tune_id --o Tune::tune_id

@enduml
